server:
  port: 8080
spring:
  application:
      name: gateway-service
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  
# mysql settings  
  datasource:
    driver: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springclouddb?autoReconnect=true&useSSL=false
    username: root
    password: root
    
      
#  cloud:
#    gateway:
#      routes:
#      - id: flight-service
#        uri: http://localhost:8081/flight
#        predicates:
#        - Path=/flight        
#      - id: location-service
#        uri: http://localhost:8082/location
#        predicates:
#        - Path=/location        
eureka:
  client:
    service-url:
      defaulZone: http://localhost:8761/eureka-server

  
#zuul:
#  routes:
#    nameservice:
#      url: http://localhost:8081/

    
    